apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: cluster-app
  namespace: database
spec:
  instances: 1
  imageName: 10.38.229.242:5000/postgresql:16.4
  storage:
    size: 5Gi
  bootstrap:
    initdb:
      database: database
      owner: admin
      secret:
        name: db-secret