apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: cluster-app
  namespace: database
spec:
  instances: 1
  imageName: registry.local:5000/postgresql:16.4
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: kubernetes.io/hostname
            operator: In
            values:
            - k3s-worker
  storage:
    size: 5Gi
  resources:
    requests:
      cpu: "100m"
      memory: "256Mi"
      ephemeral-storage: "256Mi"
    limits:
      cpu: "500m"
      memory: "512Mi"
      ephemeral-storage: "1Gi"
  bootstrap:
    initdb:
      database: database
      owner: admin
      secret:
        name: db-secret