apiVersion: v1
kind: Secret
metadata:
  name: db-secret
  namespace: database
type: kubernetes.io/basic-auth
stringData:
  username: admin
  password: password123
  url: postgresql://admin:password123@cluster-app-rw.database.svc.cluster.local:5432/database