apiVersion: v1
kind: ConfigMap
metadata:
  name: task-migrations
  namespace: database
data:
  001_init.sql: |
    -- Initial schema: avoid superuser-only extensions

    -- Tasks table (UUID provided by application)
    CREATE TABLE IF NOT EXISTS "tasks" (
      id UUID PRIMARY KEY,
      name VARCHAR(100) NOT NULL,
      description TEXT,
      user_id UUID NOT NULL,
      created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
      updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
    );

    -- Index for better query performance
    CREATE INDEX IF NOT EXISTS "idx_tasks_user_id" ON "tasks" ("user_id");
