apiVersion: batch/v1
kind: Job
metadata:
  name: task-migrations
  namespace: database
spec:
  template:
    spec:
      automountServiceAccountToken: false
      restartPolicy: OnFailure
      containers:
        - name: psql
          image: 10.38.229.242:5000/postgresql:16.4
          command: [
            "bash",
            "-lc",
            "timeout 120 sh -c 'until pg_isready -d \"$DATABASE_URL\" -q; do echo waiting for db; sleep 3; done'; psql -v ON_ERROR_STOP=1 \"$DATABASE_URL\" -f /migrations/001_init.sql"
          ]
          resources:
            requests:
              cpu: "50m"
              memory: "64Mi"
              ephemeral-storage: "128Mi"
            limits:
              memory: "128Mi"
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: url
          volumeMounts:
            - name: migrations
              mountPath: /migrations
      volumes:
        - name: migrations
          configMap:
            name: task-migrations
