kind: pipeline
type: docker
name: simple-test

steps:
  # Simple test step
  - name: hello-world
    image: alpine:latest
    commands:
      - echo "Hello from Drone CI!"
      - echo "Repository: ${DRONE_REPO_NAME}"
      - echo "Branch: ${DRONE_BRANCH}"
      - echo "Commit: ${DRONE_COMMIT_SHA}"
      - echo "Build Number: ${DRONE_BUILD_NUMBER}"

  # Test with your Rust project
  - name: test-rust-project
    image: rust:1.75
    commands:
      - echo "Testing Rust project structure..."
      - ls -la
      - test -d "apps/backend/task-api" && echo "✅ Rust project found" || echo "❌ Rust project not found"
      - test -d "apps/backend/task-api" && cd apps/backend/task-api && cargo --version
      - test -d "apps/backend/task-api" && cd apps/backend/task-api && ls -la
    when:
      event: [ push, pull_request ]

# Trigger on all branches
trigger:
  branch: [ main, master, develop, feature/* ]
  event: [ push, pull_request ]
