kind: pipeline
type: docker
name: backend-ci

steps:
  - name: rust-checks
    image: rust:1.85
    environment:
      CARGO_TERM_COLOR: always
    commands:
      - cd apps/backend/task-api
      - rustc --version; cargo --version
      - cargo fetch
      - cargo build --locked
      - cargo test --locked

  - name: docker-build-push
    image: plugins/docker:20
    privileged: true
    settings:
      repo: 10.38.229.242:5000/task-api
      registry: 10.38.229.242:5000
      insecure: true
      dockerfile: apps/backend/task-api/Dockerfile
      context: apps/backend/task-api
      tags:
        - ${DRONE_COMMIT_SHA:0:7}

  - name: update-infra-repo
    image: alpine/git:2.36.3
    environment:
      GIT_AUTHOR_NAME: drone-bot
      GIT_AUTHOR_EMAIL: drone-bot@gitea.local
      GIT_COMMITTER_NAME: drone-bot
      GIT_COMMITTER_EMAIL: drone-bot@gitea.local
      GITEA_USER:
        from_secret: gitea_user
      GITEA_TOKEN:
        from_secret: gitea_token
    commands:
      - set -euo pipefail
      - IMAGE_TAG=$(echo ${DRONE_COMMIT_SHA} | cut -c1-7)
      - REPO_URL="http://gitea.gitea.svc.cluster.local:3000/michealndoh/Cloud-native-infra.git"
      - git clone "http://${GITEA_USER}:${GITEA_TOKEN}@${REPO_URL#http://}" infra
      - cd infra
      - sed -i "s|registry.local:5000/task-api:.*|registry.local:5000/task-api:${IMAGE_TAG}|" apps/backend/task-api-deployment.yaml
      - git status --porcelain | grep . || { echo "No changes to commit"; exit 0; }
      - git add apps/backend/task-api-deployment.yaml
      - git commit -m "ci: bump task-api image to ${IMAGE_TAG}"
      - git push origin HEAD:main
    volumes:
      - name: dockersock
        path: /var/run/docker.sock

  # TODO: Re-enable infra update once secret parsing is stable

trigger:
  branch: [ main, test ]
  event: [ push, custom ]

volumes:
  - name: dockersock
    host:
      path: /var/run/docker.sock