kind: pipeline
type: docker
name: default

steps:
- name: hello-world
  image: alpine:latest
  commands:
  - echo "Hello from Drone CI!"
  - echo "This is a simple test pipeline"
  - ls -la

- name: test-rust
  image: rust:1.75
  commands:
  - echo "Testing Rust environment"
  - rustc --version
  - cargo --version
  - ls -la