kind: pipeline
type: docker
name: backend-ci

steps:
  - name: rust-checks
    image: rust:1.75
    environment:
      CARGO_TERM_COLOR: always
    commands:
      - cd apps/backend/task-api
      - rustc --version; cargo --version
      - cargo fetch
      - cargo build --locked
      - cargo test --locked

  - name: docker-build-push
    image: plugins/docker:20
    privileged: true
    settings:
      repo: registry.local:5000/task-api
      registry: registry.local:5000
      dockerfile: apps/backend/task-api/Dockerfile
      context: apps/backend/task-api
      tags:
        - ${DRONE_COMMIT_SHA:0:7}
    volumes:
      - name: dockersock
        path: /var/run/docker.sock

  - name: update-infra-repo
    image: alpine/git:2.36.3
    environment:
      GIT_AUTHOR_NAME: drone-bot
      GIT_AUTHOR_EMAIL: drone-bot@gitea.local
      GIT_COMMITTER_NAME: drone-bot
      GIT_COMMITTER_EMAIL: drone-bot@gitea.local
      GITEA_USER: michealndoh
      IMAGE_TAG: ${DRONE_COMMIT_SHA:0:7}
      GITEA_TOKEN:
        from_secret: gitea_token
    commands:
      - set -euo pipefail
      - REPO_URL="http://gitea.gitea.svc.cluster.local:3000/michealndoh/Cloud-native-infra.git"
      - git clone "http://${GITEA_USER}:${GITEA_TOKEN}@${REPO_URL#http://}" infra
      - cd infra
      - sed -i "s|registry.local:5000/task-api:.*|registry.local:5000/task-api:${IMAGE_TAG}|" apps/backend/task-api-deployment.yaml
      - git add apps/backend/task-api-deployment.yaml || true
      - git -c user.name="$GIT_AUTHOR_NAME" -c user.email="$GIT_AUTHOR_EMAIL" commit -m "ci: bump task-api image to ${IMAGE_TAG}" || echo "No changes to commit"
      - git push origin HEAD:main || true

trigger:
  branch: [ main ]
  event: [ push ]

volumes:
  - name: dockersock
    host:
      path: /var/run/docker.sock