kind: pipeline
type: docker
name: backend-ci

steps:
  - name: rust-checks
    image: 10.38.229.242:5000/rust:1.85
    environment:
      CARGO_TERM_COLOR: always
      CARGO_HOME: /cargo-home
      CARGO_REGISTRIES_CRATES_IO_PROTOCOL: sparse
    commands:
      - cd apps/backend/task-api
      - rustc --version; cargo --version
      - cargo build --offline
      - cargo test --offline
    volumes:
      - name: cargo-home
        path: /cargo-home
      - name: task-api-target
        path: /drone/src/apps/backend/task-api/target

  - name: docker-build-push
    image: 10.38.229.242:5000/plugins-docker:20
    privileged: true
    environment:
      DOCKERD_ARGS: "--insecure-registry registry.local:5000 --insecure-registry 10.38.229.242:5000"
    settings:
      repo: 10.38.229.242:5000/task-api
      registry: 10.38.229.242:5000
      insecure: true
      dockerfile: apps/backend/task-api/Dockerfile
      context: apps/backend/task-api
      build_args:
        - RUST_BASE=10.38.229.242:5000/rust:1.85
        - RUNTIME_BASE=10.38.229.242:5000/debian:bookworm-slim
      tags:
        - ${DRONE_COMMIT_SHA:0:7}
        - latest
      cache_from:
        - 10.38.229.242:5000/task-api:latest

  - name: update-infra-repo
    image: 10.38.229.242:5000/alpine-git:2.36.3
    environment:
      GIT_AUTHOR_NAME: drone-bot
      GIT_AUTHOR_EMAIL: drone-bot@gitea.local
      GIT_COMMITTER_NAME: drone-bot
      GIT_COMMITTER_EMAIL: drone-bot@gitea.local
    commands:
      - set -euo pipefail
      - IMAGE_TAG=$(echo ${DRONE_COMMIT_SHA} | cut -c1-7)
      - REPO_URL_WITH_AUTH="http://michealndoh:89d192d125811a493ae841b42628e3bc7283af16@gitea.local/michealndoh/Cloud-native-infra.git"
      - git clone "$REPO_URL_WITH_AUTH" infra
      - cd infra
      - |
          awk -v tag="$IMAGE_TAG" 'BEGIN{FS=OFS=""} /^[[:space:]]*image:[[:space:]].*task-api:/ { match($0, /^[[:space:]]*/); indent=substr($0, RSTART, RLENGTH); print indent "image: 10.38.229.242:5000/task-api:" tag; next } { print }' apps/backend/task-api-deployment.yaml > /tmp/manifest
          mv /tmp/manifest apps/backend/task-api-deployment.yaml
      - |
          if git status --porcelain | grep .; then
            git add apps/backend/task-api-deployment.yaml
            git commit -m "ci: bump task-api image to ${IMAGE_TAG}"
            git push origin HEAD:main
          else
            echo "No changes to commit"
          fi
    volumes:
      - name: dockersock
        path: /var/run/docker.sock

  # TODO: Re-enable infra update once secret parsing is stable

trigger:
  branch: [ main, test ]
  event: [ push, custom ]

volumes:
  - name: dockersock
    host:
      path: /var/run/docker.sock
  - name: cargo-home
    host:
      path: /var/lib/drone-cache/cargo-home
  - name: task-api-target
    host:
      path: /var/lib/drone-cache/task-api-target