kind: pipeline
type: docker
name: simple-test

steps:
  # Simple test step
  - name: hello-world
    image: alpine:latest
    commands:
      - echo "Hello from Drone CI!"
      - echo "Repository: ${DRONE_REPO_NAME}"
      - echo "Branch: ${DRONE_BRANCH}"
      - echo "Commit: ${DRONE_COMMIT_SHA}"
      - echo "Build Number: ${DRONE_BUILD_NUMBER}"

  # Test with your Rust project
  - name: test-rust-project
    image: rust:1.75
    commands:
      - echo "Testing Rust project structure..."
      - ls -la
      - if [ -d "apps/backend/task-api" ]; then
          echo "✅ Rust project found";
          cd apps/backend/task-api;
          cargo --version;
          ls -la;
        else
          echo "❌ Rust project not found";
          exit 1;
        fi
    when:
      event: [ push, pull_request ]

# Trigger on all branches
trigger:
  branch: [ main, master, develop, feature/* ]
  event: [ push, pull_request ]