kind: pipeline
type: docker
name: backend-ci

steps:
  - name: rust-checks
    image: rust:1.85
    environment:
      CARGO_TERM_COLOR: always
    commands:
      - cd apps/backend/task-api
      - rustc --version; cargo --version
      - cargo fetch
      - cargo build --locked
      - cargo test --locked

  - name: docker-build-push
    image: plugins/docker:20
    privileged: true
    settings:
      repo: 10.38.229.242:5000/task-api
      registry: 10.38.229.242:5000
      insecure: true
      dockerfile: apps/backend/task-api/Dockerfile
      context: apps/backend/task-api
      tags:
        - ${DRONE_COMMIT_SHA:0:7}
    volumes:
      - name: dockersock
        path: /var/run/docker.sock

  # TODO: Re-enable infra update once secret parsing is stable

trigger:
  branch: [ main, test ]
  event: [ push, custom ]

volumes:
  - name: dockersock
    host:
      path: /var/run/docker.sock