apiVersion: v1
kind: Pod
metadata:
  name: keycloak-fixed
  namespace: keycloak
  labels:
    app: keycloak
  annotations:
    linkerd.io/inject: enabled
    # Keep proxy configuration; main fix is resource guarantees and tolerations
spec:
  restartPolicy: Always
  tolerations:
    - key: node.kubernetes.io/disk-pressure
      operator: Exists
      effect: NoSchedule
    - key: node.kubernetes.io/memory-pressure
      operator: Exists
      effect: NoSchedule
  containers:
    - name: keycloak
      image: registry.local:5000/keycloak:latest
      imagePullPolicy: Always
      args: ["start-dev"]
      ports:
        - containerPort: 8080
      resources:
        requests:
          cpu: 250m
          memory: 1Gi
          ephemeral-storage: 512Mi
        limits:
          cpu: 1
          memory: 2Gi
          ephemeral-storage: 2Gi
      envFrom:
        - configMapRef:
            name: keycloak-config
        - secretRef:
            name: keycloak-db-secret
      readinessProbe:
        httpGet:
          path: /
          port: 8080
        initialDelaySeconds: 15
        periodSeconds: 10
        timeoutSeconds: 2
        failureThreshold: 12
      startupProbe:
        httpGet:
          path: /
          port: 8080
        initialDelaySeconds: 5
        periodSeconds: 10
        timeoutSeconds: 5
        failureThreshold: 60
    - name: linkerd-proxy
      image: cr.l5d.io/linkerd/proxy:edge-25.9.1
      imagePullPolicy: IfNotPresent
      ports:
        - containerPort: 4143
          name: linkerd-proxy
        - containerPort: 4191
          name: linkerd-admin
      resources:
        requests:
          cpu: 50m
          memory: 64Mi
          ephemeral-storage: 128Mi
        limits:
          cpu: 250m
          memory: 256Mi
          ephemeral-storage: 1Gi
  initContainers:
    - name: linkerd-init
      image: cr.l5d.io/linkerd/proxy-init:v2.4.3
      resources:
        requests:
          cpu: 10m
          memory: 32Mi
          ephemeral-storage: 64Mi
        limits:
          cpu: 100m
          memory: 128Mi
          ephemeral-storage: 512Mi
      securityContext:
        capabilities:
          add: ["NET_ADMIN", "NET_RAW"]
