apiVersion: v1
kind: Pod
metadata:
  name: task-api-fixed
  namespace: backend
  labels:
    app: task-api
  annotations:
    linkerd.io/inject: enabled
spec:
  restartPolicy: Always
  tolerations:
    - key: node.kubernetes.io/disk-pressure
      operator: Exists
      effect: NoSchedule
    - key: node.kubernetes.io/memory-pressure
      operator: Exists
      effect: NoSchedule
  containers:
    - name: task-api
      image: registry.local:5000/task-api:latest
      imagePullPolicy: Always
      command: ["/app/task-api"]
      ports:
        - containerPort: 3000
      resources:
        requests:
          cpu: 100m
          memory: 256Mi
          ephemeral-storage: 256Mi
        limits:
          cpu: 500m
          memory: 512Mi
          ephemeral-storage: 1Gi
      envFrom:
        - configMapRef:
            name: task-api-config
        - secretRef:
            name: task-api-secrets
      readinessProbe:
        tcpSocket:
          port: 3000
        initialDelaySeconds: 5
        periodSeconds: 10
        timeoutSeconds: 2
        failureThreshold: 6
      startupProbe:
        tcpSocket:
          port: 3000
        initialDelaySeconds: 2
        periodSeconds: 5
        timeoutSeconds: 2
        failureThreshold: 30
    - name: linkerd-proxy
      image: cr.l5d.io/linkerd/proxy:edge-25.9.1
      imagePullPolicy: IfNotPresent
      ports:
        - containerPort: 4143
          name: linkerd-proxy
        - containerPort: 4191
          name: linkerd-admin
      resources:
        requests:
          cpu: 25m
          memory: 64Mi
          ephemeral-storage: 64Mi
        limits:
          cpu: 200m
          memory: 128Mi
          ephemeral-storage: 512Mi
  initContainers:
    - name: linkerd-init
      image: cr.l5d.io/linkerd/proxy-init:v2.4.3
      resources:
        requests:
          cpu: 10m
          memory: 16Mi
          ephemeral-storage: 32Mi
        limits:
          cpu: 100m
          memory: 64Mi
          ephemeral-storage: 256Mi
      securityContext:
        capabilities:
          add: ["NET_ADMIN", "NET_RAW"]
