apiVersion: apps/v1
kind: Deployment
metadata:
  name: keycloak
  namespace: keycloak
  labels:
    app: keycloak
  annotations:
    linkerd.io/inject: enabled
spec:
  replicas: 1
  selector:
    matchLabels:
      app: keycloak
  template:
    metadata:
      labels:
        app: keycloak
      annotations:
        linkerd.io/inject: enabled
    spec:
      containers:
        - name: keycloak
          image: 10.38.229.242:5000/keycloak:latest
          args: ["start-dev"]
          envFrom:
            - configMapRef:
                name: keycloak-config
            - secretRef:
                name: keycloak-db-secret
          ports:
            - containerPort: 8080
