apiVersion: apps/v1
kind: Deployment
metadata:
  name: task-api
  namespace: backend
  annotations:
    linkerd.io/inject: disabled
spec:
  replicas: 1
  selector:
    matchLabels:
      app: task-api
  template:
    metadata:
      labels:
        app: task-api
      annotations:
        linkerd.io/inject: disabled
    spec:
      nodeSelector:
        kubernetes.io/hostname: k3s-worker
      containers:
        - name: task-api
          image: registry.local:5000/task-api@sha256:edc3578d7621b74e1ad124200c34181c23dbdee570430ac25352e894bda2d66d
          ports:
            - containerPort: 3000
          resources:
            requests:
              cpu: "50m"
              memory: "64Mi"
              ephemeral-storage: "256Mi"
            limits:
              cpu: "200m"
              memory: "256Mi"
              ephemeral-storage: "1Gi"
          env:
            - name: RUST_LOG
              value: info
            - name: LOG_OUTPUT
              value: stdout
          envFrom:
            - configMapRef:
                name: task-api-config
            - secretRef:
                name: task-api-secrets
