apiVersion: apps/v1
kind: Deployment
metadata:
  name: task-api
  namespace: backend
  annotations:
    linkerd.io/inject: enabled
spec:
  replicas: 1
  selector:
    matchLabels:
      app: task-api
  template:
    metadata:
      labels:
        app: task-api
      annotations:
        linkerd.io/inject: enabled
    spec:
      containers:
        - name: task-api
          image: 10.38.229.242:5000/task-api:c109aa5
          ports:
            - containerPort: 3000
          envFrom:
            - configMapRef:
                name: task-api-config
            - secretRef:
                name: task-api-secrets
