apiVersion: v1
kind: Namespace
metadata:
  name: ci
---
apiVersion: v1
kind: Secret
metadata:
  name: drone-secrets
  namespace: ci
type: Opaque
stringData:
  DRONE_GITEA_CLIENT_ID: "3da300e6-d959-4ce4-bd6f-61d617ac058d"
  DRONE_GITEA_CLIENT_SECRET: "gto_kk2edmg6e2zharziciog6dxli627r4yfllnrdqf3oarhubbkyalq"
  DRONE_RPC_SECRET: "supersecret"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: drone-data
  namespace: ci
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  storageClassName: local-path
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: drone-server
  namespace: ci
  labels:
    app: drone-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: drone-server
  template:
    metadata:
      labels:
        app: drone-server
    spec:
      automountServiceAccountToken: false
      hostAliases:
        - ip: "10.38.229.161"
          hostnames:
            - "gitea.local"
        - ip: "10.38.229.69"
          hostnames:
            - "gitea.local"
      containers:
        - name: server
          image: 10.38.229.242:5000/drone:2
          env:
            - name: DRONE_GITEA_SERVER
              value: "http://gitea.local"
            - name: DRONE_SERVER_HOST
              value: "drone.local"
            - name: DRONE_SERVER_PROTO
              value: "http"
            - name: DRONE_SERVER_PORT
              value: ":80"
            - name: DRONE_RPC_SECRET
              valueFrom:
                secretKeyRef:
                  name: drone-secrets
                  key: DRONE_RPC_SECRET
            - name: DRONE_GITEA_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: drone-secrets
                  key: DRONE_GITEA_CLIENT_ID
            - name: DRONE_GITEA_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: drone-secrets
                  key: DRONE_GITEA_CLIENT_SECRET
            - name: DRONE_USER_CREATE
              value: "username:michealndoh,admin:true"
            - name: DRONE_DATABASE_DRIVER
              value: "sqlite3"
            - name: DRONE_DATABASE_DATASOURCE
              value: "/data/database.sqlite"
          ports:
            - containerPort: 80
          volumeMounts:
            - name: drone-data
              mountPath: /data
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              memory: "256Mi"
      volumes:
        - name: drone-data
          persistentVolumeClaim:
            claimName: drone-data
---
apiVersion: v1
kind: Service
metadata:
  name: drone-server
  namespace: ci
spec:
  selector:
    app: drone-server
  ports:
    - port: 80
      targetPort: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: drone
  namespace: ci
spec:
  rules:
    - host: drone.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: drone-server
                port:
                  number: 80
